new-black/eva-defaults

translation/en-US.json

https://n6k.atlassian.net/browse/OPTR-17352

PCI Question-Translation for did change occur question

---

appsettings.json

added three app settings

---

admin_modules_new.json

- added Compliance module to the list of modules
- **I am open for suggestions regarding the module description**

feat(compliance): add compliance module

---

appsettings.json

Setting to influence which tasks are present

TaskPresence.json

---

appsettings.json

https://n6k.atlassian.net/browse/OPTR-22730

feat(rogue order update): adds app setting defaults

---

appsettings.json

Added an app settings for this ticket: https://n6k.atlassian.net/browse/OPTR-24076

added setting

---

appsettings.json

https://n6k.atlassian.net/browse/OPTR-24091

feat(price-variations): add app setting default

---

appsettings.json

https://n6k.atlassian.net/browse/OPTR-24596

feat(customer-cases): add app setting default

---

appsettings.json

https://n6k.atlassian.net/browse/OPTR-24521

feat(back-in-stock): add app setting default

---

appsettings.json

feat(app-scan-behaviour): add app scan behaviour setting

---

appsettings.json

https://n6k.atlassian.net/browse/OPTR-25481

feat(app): new app setting

---

appsettings.json

- updated `App:Returns:PrefilledOrganizationUnit` app setting type, added new options, reference ticket and updated the description of the setting

feat(optr-26228): add new options to prefilledou app setting

---

appsettings.json

https://n6k.atlassian.net/browse/OPTR-27466

feat(app setting): show user bough products

---

appsettings.json

PR to introduce the app setting needed for [OPTR-27206]( https://n6k.atlassian.net/jira/software/c/projects/OPTR/boards/109?selectedIssue=OPTR-27206)

feat(hide-delete-print-tasks): add app setting

---

appsettings.json

https://n6k.atlassian.net/browse/OPTR-27410

feat: add setting to show miles

---

appsettings.json

https://n6k.atlassian.net/browse/OPTR-28031

feat: add setting search show discount

---

appsettings.json

https://n6k.atlassian.net/browse/OPTR-27934

feat(app setting): pending bank deposits checkbox

---

appsettings.json

https://n6k.atlassian.net/browse/OPTR-27990

feat: add setting for unified orders filter option

---

appsettings.json

https://n6k.atlassian.net/browse/OPTR-28632

feat(app setting): show organisations w/o stock

---

appsettings.json

https://n6k.atlassian.net/browse/OPTR-28901

add barcode custom field

---

appsettings.json

https://n6k.atlassian.net/browse/OPTR-27999

feat(OPTR-27999): Partial Payment setting

---

appsettings.json

https://n6k.atlassian.net/browse/OPTR-32582

feat(show signature on sfd): update setting default

---

appsettings.json

https://n6k.atlassian.net/browse/OPTR-32674

feat: add app setting

---

appsettings.json

https://n6k.atlassian.net/browse/OPTR-35219

feat: add global blue prompt setting

---

appsettings.json

Converts setting from object to string array

feat: convert product properties setting

---

appsettings.json

Reverts new-black/eva-defaults#82

Revert "feat(OPTR-36463): add cashdrawer hideopenbutton setting"

---

appsettings.json

https://n6k.atlassian.net/browse/OPTR-39569

Create App:PickTask:EnforceScanning setting

---

appsettings.json

https://n6k.atlassian.net/browse/OPTR-40302

feat: add order complete survey id setting

---

appsettings.json

https://github.com/new-black/eva-app-suite/pull/2630

Add ShipFromStore:ShowTrackingInput app setting

---

appsettings.json

https://n6k.atlassian.net/browse/OPTR-41221

feat: pickup availability include cross border stores
